Repository UMC-6th-DutchTogether/DutchTogether_BE, pull requests merged in 2024-07, with the labels that each got.

#3 DB 연동
  build.gradle
  src/main/resources/application.yml
Labels: feat

#5 [FEAT] Swagger 세팅
  src/main/java/com/umc/DutchTogether/Root/RootController.java
  src/main/java/com/umc/DutchTogether/config/SwaggerConfig.java
Labels: feat

#7 [FEAT] 엔티티 작성
  src/main/java/com/umc/DutchTogether/domain/meeting/entity/Meeting.java
  src/main/java/com/umc/DutchTogether/domain/payer/entity/Payer.java
  src/main/java/com/umc/DutchTogether/domain/settlement/entity/Settlement.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/entity/SettlementSettler.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/entity/SettlementStatus.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/entity/SettlementStatus.java
  src/main/java/com/umc/DutchTogether/domain/settler/entity/Settler.java
  src/main/java/com/umc/DutchTogether/global/common/BaseEntity.java
  src/main/java/com/umc/DutchTogether/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: feat

#11 [FEAT] 응답 형식 통일, 에러 핸들러, CORS 처리
  src/main/java/com/umc/DutchTogether/global/apiPayload/ApiResponse.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/BaseCode.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/BaseErrorCode.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/ErrorReasonDTO.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/ReasonDTO.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/status/SuccessStatus.java
  src/main/java/com/umc/DutchTogether/global/config/WebConfig.java
  src/main/java/com/umc/DutchTogether/global/exception/ExceptionAdvice.java
  src/main/java/com/umc/DutchTogether/global/exception/GeneralException.java
  src/main/java/com/umc/DutchTogether/global/exception/handler/ErrorHandler.java
  src/main/resources/application.yml
Labels: feat

#13 [FEAT] 나만 정산하기 API 구축
  .DS_Store
  src/main/java/com/umc/DutchTogether/domain/meeting/controller/MeetingController.java
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingCreateRequestDto.java
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingCreateResponseDto.java
  src/main/java/com/umc/DutchTogether/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingService.java
  src/main/java/com/umc/DutchTogether/domain/payer/entity/Payer.java
  src/main/java/com/umc/DutchTogether/domain/payer/repository/PayerRepository.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerService.java
  src/main/java/com/umc/DutchTogether/domain/settlement/controller/SingleSettlementController.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SingleSettlementCreateRequestDto.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SingleSettlementCreateResponseDto.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SingleSettlementInfoResponseDto.java
  src/main/java/com/umc/DutchTogether/domain/settlement/entity/Settlement.java
  src/main/java/com/umc/DutchTogether/domain/settlement/repository/SettlementRepository.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementService.java
  src/main/java/com/umc/DutchTogether/domain/settler/repository/SettlerRepository.java
  src/main/java/com/umc/DutchTogether/global/exception/ResourceNotFoundException.java
Labels: feat

#15 [FEAT] '나만 정산하기' 검증 추가 및 정산 반환값 추가
  .DS_Store
  src/main/java/com/umc/DutchTogether/domain/meeting/controller/MeetingController.java
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingCreateRequestDto.java
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingCreateResponseDto.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingService.java
  src/main/java/com/umc/DutchTogether/domain/meeting/validation/ConditionalValidPassword.java
  src/main/java/com/umc/DutchTogether/domain/meeting/validation/ConditionalValidPasswordValidator.java
  src/main/java/com/umc/DutchTogether/domain/meeting/validation/PasswordValidator.java
  src/main/java/com/umc/DutchTogether/domain/meeting/validation/ValidPassword.java
  src/main/java/com/umc/DutchTogether/domain/settlement/controller/SingleSettlementController.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SingleSettlementCreateRequestDto.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SingleSettlementCreateResponseDto.java
  src/main/java/com/umc/DutchTogether/domain/settlement/entity/Settlement.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementService.java
  src/main/java/com/umc/DutchTogether/global/validation/ValidationUtils.java
Labels: feat, refactor

#17 [FIX] WebConfig에 도메인 추가
  src/main/java/com/umc/DutchTogether/global/config/WebConfig.java
Labels: fix

#20 [REFACTOR] ID 검증 수정
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/status/ErrorStatus.java
Labels: refactor

#26 [REFACTOR] settlement 도메인 구조 및 응답 통일
  src/main/java/com/umc/DutchTogether/DutchTogetherApplication.java
  src/main/java/com/umc/DutchTogether/domain/meeting/controller/MeetingRestController.java
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingRequest.java
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingResponse.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlement/controller/SettlementRestController.java
  src/main/java/com/umc/DutchTogether/domain/settlement/controller/SingleSettlementController.java
  src/main/java/com/umc/DutchTogether/domain/settlement/converter/SettlementConverter.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SettlementRequest.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SettlementResponse.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SingleSettlementCreateRequestDto.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SingleSettlementCreateResponseDto.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SingleSettlementInfoResponseDto.java
  src/main/java/com/umc/DutchTogether/domain/settlement/entity/Settlement.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementCommandService.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementQueryService.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementService.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/exception/ResourceNotFoundException.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/exception/handler/SettlementHandler.java
  src/main/java/com/umc/DutchTogether/global/validation/ValidationUtils.java
Labels: refactor

#27 [REFACTOR] settlement api 관련 에러코드 추가
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/status/ErrorStatus.java
Labels: refactor

#30 [FIX] 검증 수정,통일
  src/main/java/com/umc/DutchTogether/domain/meeting/controller/MeetingRestController.java
  src/main/java/com/umc/DutchTogether/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingRequest.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlement/controller/SettlementRestController.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SettlementRequest.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/exception/ExceptionAdvice.java
  src/main/java/com/umc/DutchTogether/global/validation/annotation/ExistMeeting.java
  src/main/java/com/umc/DutchTogether/global/validation/annotation/ValidateMeeting.java
  src/main/java/com/umc/DutchTogether/global/validation/annotation/ValidatePassword.java
  src/main/java/com/umc/DutchTogether/global/validation/validator/ExistMeetingValidator.java
  src/main/java/com/umc/DutchTogether/global/validation/validator/MeetingValidator.java
  src/main/java/com/umc/DutchTogether/global/validation/validator/PasswordValidator.java
Labels: fix
