Repository UMC-6th-DutchTogether/DutchTogether_BE, pull requests merged in 2024-08, with the labels that each got.

#31 [FIX] CORS 에러 처리
  src/main/java/com/umc/DutchTogether/global/config/WebConfig.java
Labels: fix

#33 [FIX] 프론트 도메인 CORS 추가
  src/main/java/com/umc/DutchTogether/global/config/WebConfig.java
Labels: fix

#35 [FEAT] 나만 정산하기 정보 조회 API 구현
  src/main/java/com/umc/DutchTogether/domain/meeting/controller/MeetingRestController.java
  src/main/java/com/umc/DutchTogether/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingResponse.java
  src/main/java/com/umc/DutchTogether/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SettlementResponse.java
  src/main/java/com/umc/DutchTogether/domain/settlement/repository/SettlementRepository.java
Labels: feat

#38 [FIX] 모임 링크 오타 수정
  src/main/java/com/umc/DutchTogether/domain/meeting/converter/MeetingConverter.java
Labels: fix

#40 [REFACTOR] 정산 현황 보기 API 수정
  .github/workflows/dev_deploy.yml
  src/main/java/com/umc/DutchTogether/domain/meeting/controller/MeetingRestController.java
  src/main/java/com/umc/DutchTogether/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/payer/repository/PayerRepository.java
  src/main/java/com/umc/DutchTogether/domain/settlement/controller/SettlementRestController.java
  src/main/java/com/umc/DutchTogether/domain/settlement/entity/Settlement.java
  src/main/java/com/umc/DutchTogether/domain/settlement/repository/SettlementRepository.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/entity/SettlementSettler.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/entity/Status.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/repository/SettlementSettlerRepository.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/controller/SettlementStatusRestController.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/converter/SettlementStatusConverter.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/dto/SettlementStatusRequest.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/dto/SettlementStatusResponse.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/entity/SettlementStatus.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/respoistory/SettlementStatusRepository.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusCommandService.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusQueryService.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settler/repository/SettlerRepository.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/DutchTogether/global/common/BaseEntity.java
  src/main/java/com/umc/DutchTogether/root/RootController.java
  src/main/java/com/umc/DutchTogether/root/RootResponseDTO.java
Labels: refactor

#44 [FIX] 모임 생성 API 연결 지연 수정
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingRequest.java
Labels: fix

#46 [FEAT] /api/payers 구현
  src/main/java/com/umc/DutchTogether/domain/meeting/controller/MeetingRestController.java
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingRequest.java
  src/main/java/com/umc/DutchTogether/domain/payer/controller/PayerRestController.java
  src/main/java/com/umc/DutchTogether/domain/payer/converter/PayerConverter.java
  src/main/java/com/umc/DutchTogether/domain/payer/dto/PayerRequest.java
  src/main/java/com/umc/DutchTogether/domain/payer/dto/PayerResponse.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerCommandService.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerService.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementService.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/entity/SettlementSettler.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusQueryServiceImpl.java
Labels: feat

#48 [REFACTOR] Payer 생성 관련
  src/main/java/com/umc/DutchTogether/domain/payer/dto/PayerRequest.java
  src/main/java/com/umc/DutchTogether/domain/payer/repository/PayerRepository.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerCommandServiceImpl.java
Labels: refactor

#52 [FEAT] 정산 완료하기 API 구현
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/controller/SettlementSettlerRestController.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/converter/SettlementSettlerConverter.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/dto/SettlementSettlerRequest.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/dto/SettlementSettlerResponse.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/entity/SettlementSettler.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/repository/SettlementSettlerRepository.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/service/SettlementSettlerCommandService.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/service/SettlementSettlerCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/global/validation/annotation/UniqueSettler.java
  src/main/java/com/umc/DutchTogether/global/validation/validator/UniqueSettlerValidator.java
Labels: feat

#53 [REFACTOR] 정산 완료하기 예외처리 및 기능 수정
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/dto/SettlementSettlerRequest.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/entity/SettlementSettler.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/repository/SettlementSettlerRepository.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/service/SettlementSettlerCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settler/repository/SettlerRepository.java
  src/main/java/com/umc/DutchTogether/global/validation/annotation/ExistSettlement.java
  src/main/java/com/umc/DutchTogether/global/validation/validator/ExistSettlementValidator.java
  src/main/java/com/umc/DutchTogether/global/validation/validator/UniqueSettlerValidator.java
Labels: refactor

#55 [FIX] workflow update
  .github/workflows/dev_deploy.yml
Labels: fix

#58 [FEAT] 정산하기 추가 API, 정산자 저장 API
  src/main/java/com/umc/DutchTogether/domain/payer/dto/PayerResponse.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlement/controller/SettlementRestController.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SettlementRequest.java
  src/main/java/com/umc/DutchTogether/domain/settlement/entity/Settlement.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementCommandService.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settler/controller/SettlerRestController.java
  src/main/java/com/umc/DutchTogether/domain/settler/dto/SettlerRequest.java
  src/main/java/com/umc/DutchTogether/domain/settler/dto/SettlerResponse.java
  src/main/java/com/umc/DutchTogether/domain/settler/service/SettlerCommandService.java
  src/main/java/com/umc/DutchTogether/domain/settler/service/SettlerCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settler/service/SettlerQueryService.java
Labels: feat

#65 [FEAT] 영수증 인식 API 구현
  .gitignore
  build.gradle
  src/main/java/com/umc/DutchTogether/domain/receipt/controller/ReceiptRestController.java
  src/main/java/com/umc/DutchTogether/domain/receipt/converter/ReceiptConverter.java
  src/main/java/com/umc/DutchTogether/domain/receipt/dto/ReceiptRequest.java
  src/main/java/com/umc/DutchTogether/domain/receipt/dto/ReceiptResponse.java
  src/main/java/com/umc/DutchTogether/domain/receipt/entity/Receipt.java
  src/main/java/com/umc/DutchTogether/domain/receipt/repository/ReceiptRepository.java
  src/main/java/com/umc/DutchTogether/domain/receipt/service/ReceiptCommandService.java
  src/main/java/com/umc/DutchTogether/domain/receipt/service/ReceiptCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlement/entity/Settlement.java
  src/main/java/com/umc/DutchTogether/global/aws/s3/AmazonS3Manager.java
  src/main/java/com/umc/DutchTogether/global/aws/s3/Uuid.java
  src/main/java/com/umc/DutchTogether/global/aws/s3/UuidRepository.java
  src/main/java/com/umc/DutchTogether/global/clova/OCRService.java
  src/main/java/com/umc/DutchTogether/global/config/AmazonConfig.java
Labels: feat

#70 [FEAT] 여러명이 계산해요 화면 API 개발
  src/main/java/com/umc/DutchTogether/domain/payer/controller/PayerRestController.java
  src/main/java/com/umc/DutchTogether/domain/payer/dto/PayerResponse.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerQueryService.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlement/converter/SettlementConverter.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/repository/SettlementSettlerRepository.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/service/SettlementSettlerCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settler/controller/SettlerRestController.java
  src/main/java/com/umc/DutchTogether/domain/settler/dto/SettlerResponse.java
  src/main/java/com/umc/DutchTogether/domain/settler/repository/SettlerRepository.java
  src/main/java/com/umc/DutchTogether/domain/settler/service/SettlerQueryService.java
  src/main/java/com/umc/DutchTogether/domain/settler/service/SettlerQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/status/ErrorStatus.java
Labels: feat

#72 [FIX] 정산자 저장 API
  src/main/java/com/umc/DutchTogether/domain/settler/service/SettlerCommandServiceImpl.java
Labels: fix

#73 [FEAT] 정산현황 로그인 API 구현
  build.gradle
  src/main/java/com/umc/DutchTogether/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/controller/SettlementStatusRestController.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/converter/SettlementStatusConverter.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/dto/SettlementStatusRequest.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/dto/SettlementStatusResponse.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/dto/Token.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusCommandService.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/DutchTogether/global/config/SecurityConfig.java
  src/main/java/com/umc/DutchTogether/global/security/JwtFilter.java
  src/main/java/com/umc/DutchTogether/global/security/JwtToken.java
  src/main/java/com/umc/DutchTogether/global/security/TokenProvider.java
Labels: feat

#75 [FIX] build.gradle 수정
  build.gradle
Labels: fix

#76 [REFACTOR] 아이디 중복 처리, 정산현황 응답 수정
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingRequest.java
  src/main/java/com/umc/DutchTogether/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/service/SettlementSettlerCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/converter/SettlementStatusConverter.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/dto/SettlementStatusResponse.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/DutchTogether/global/security/TokenProvider.java
  src/main/java/com/umc/DutchTogether/global/validation/annotation/UniqueMeeting.java
  src/main/java/com/umc/DutchTogether/global/validation/validator/UniqueMeetingValidator.java
Labels: refactor

#78 [FEAT] 정산현황 정산자 검색 API 구현
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/repository/SettlementSettlerRepository.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/controller/SettlementStatusRestController.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/converter/SettlementStatusConverter.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusQueryService.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusQueryServiceImpl.java
Labels: feat

#80 [REFACTOR] 정산 영수증 첨부 추가
  src/main/java/com/umc/DutchTogether/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingResponse.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/receipt/entity/Receipt.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SettlementRequest.java
  src/main/java/com/umc/DutchTogether/domain/settlement/entity/Settlement.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/DutchTogether/global/validation/annotation/ExistReceipt.java
  src/main/java/com/umc/DutchTogether/global/validation/validator/ExistReceiptValidator.java
Labels: refactor

#81 [REFACTOR] Payer - Service : 예외처리 및 컨버터 분리
  src/main/java/com/umc/DutchTogether/domain/payer/converter/PayerConverter.java
  src/main/java/com/umc/DutchTogether/domain/payer/dto/PayerRequest.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlement/converter/SettlementConverter.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/exception/handler/SettlementSettlerHandler.java
Labels: refactor

#83 [REFACTOR] settler 관련 메소드
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settler/controller/SettlerRestController.java
  src/main/java/com/umc/DutchTogether/domain/settler/converter/SettlerConverter.java
  src/main/java/com/umc/DutchTogether/domain/settler/dto/SettlerRequest.java
  src/main/java/com/umc/DutchTogether/domain/settler/service/SettlerCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settler/service/SettlerQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/status/ErrorStatus.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/exception/handler/SettlerHandler.java
Labels: refactor

#85 [FIX] settlement-settler - status 디폴트 값 설정
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/entity/SettlementSettler.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusCommandServiceImpl.java
Labels: fix

#87 [REFACTOR] 모임 생성에서 모임 이름 저장 분리
  src/main/java/com/umc/DutchTogether/domain/meeting/controller/MeetingRestController.java
  src/main/java/com/umc/DutchTogether/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingRequest.java
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingResponse.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingCommandService.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingCommandServiceImpl.java
Labels: refactor

#90 [FIX] 결제자 저장 방식 수정
  src/main/java/com/umc/DutchTogether/domain/payer/controller/PayerRestController.java
  src/main/java/com/umc/DutchTogether/domain/payer/converter/PayerConverter.java
  src/main/java/com/umc/DutchTogether/domain/payer/dto/PayerRequest.java
  src/main/java/com/umc/DutchTogether/domain/payer/entity/Payer.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerCommandService.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/status/ErrorStatus.java
Labels: fix

#93 [FEAT] 정산현황 - 정산자 추가 api
  src/main/java/com/umc/DutchTogether/domain/settlementSettler/repository/SettlementSettlerRepository.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/controller/SettlementStatusRestController.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/dto/SettlementStatusRequest.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/respoistory/SettlementStatusRepository.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusCommandService.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/exception/handler/SettlementStatusHandler.java
Labels: feat

#94 [FIX] Post : /api/settler 수정
  src/main/java/com/umc/DutchTogether/domain/settler/dto/SettlerRequest.java
  src/main/java/com/umc/DutchTogether/domain/settler/service/SettlerCommandServiceImpl.java
Labels: fix

#96 [FIX] singleSettlementResultDTO - settlementId 추가
  src/main/java/com/umc/DutchTogether/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingResponse.java
Labels: fix

#98 [FIX] 나만 정산하기 정보 조회 오류 수정
  src/main/java/com/umc/DutchTogether/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingQueryServiceImpl.java
Labels: fix

#99 [REFACTOR] 정산자 검색 에러메시지 수정
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusQueryServiceImpl.java
Labels: refactor

#101 [FIX] 아이디 비밀번호 중복체크 방식 변경
  src/main/java/com/umc/DutchTogether/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/umc/DutchTogether/global/validation/validator/UniqueMeetingValidator.java
Labels: fix

#104 [FIX] 오타 수정
  src/main/java/com/umc/DutchTogether/domain/settler/controller/SettlerRestController.java
Labels: fix

#107 [FIX] 결제자 중복 처리
  src/main/java/com/umc/DutchTogether/domain/payer/repository/PayerRepository.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlement/repository/SettlementRepository.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/status/ErrorStatus.java
Labels: fix

#108 [FEAT] 나만 정산하기 정보 확인 API
  src/main/java/com/umc/DutchTogether/domain/meeting/controller/MeetingRestController.java
  src/main/java/com/umc/DutchTogether/domain/meeting/dto/MeetingResponse.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingQueryServiceImpl.java
Labels: feat

#109 [FEAT] 나만 정산하기 정보 확인 API
  src/main/java/com/umc/DutchTogether/domain/meeting/controller/MeetingRestController.java
  src/main/java/com/umc/DutchTogether/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingQueryServiceImpl.java
Labels: feat

#112 [FEAT][FIX] 여러명 정산하기 settlement 생성 관련
  src/main/java/com/umc/DutchTogether/domain/payer/repository/PayerRepository.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerCommandService.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/domain/settlement/controller/SettlementRestController.java
  src/main/java/com/umc/DutchTogether/domain/settlement/converter/SettlementConverter.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SettlementRequest.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SettlementResponse.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementCommandService.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementCommandServiceImpl.java
Labels: feat

#113 [FIX] 오타 , 누락된 부분 추가
  src/main/java/com/umc/DutchTogether/domain/settlement/controller/SettlementRestController.java
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SettlementRequest.java
  src/main/java/com/umc/DutchTogether/domain/settlement/service/SettlementCommandServiceImpl.java
Labels: fix

#117 [FIX] 영수증 url 응답 에러 수정
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingQueryServiceImpl.java
Labels: fix

#119 [FIX] 응답 totalAmout -> totalAmount/num_people
  src/main/java/com/umc/DutchTogether/domain/payer/converter/PayerConverter.java
  src/main/java/com/umc/DutchTogether/domain/payer/dto/PayerResponse.java
  src/main/java/com/umc/DutchTogether/domain/payer/service/PayerQueryServiceImpl.java
  src/main/java/com/umc/DutchTogether/global/apiPayload/code/status/ErrorStatus.java
Labels: fix

#121 [FIX] settler 저장 시 정산 참여인원 업데이트
  src/main/java/com/umc/DutchTogether/domain/settler/service/SettlerCommandServiceImpl.java
Labels: fix

#123 [FIX] link 모임 형태 별로 다르게 전달
  src/main/java/com/umc/DutchTogether/domain/meeting/controller/MeetingRestController.java
  src/main/java/com/umc/DutchTogether/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingQueryService.java
  src/main/java/com/umc/DutchTogether/domain/meeting/service/MeetingQueryServiceImpl.java
Labels: fix

#125 [REFACTOR] 여러 명 정산 링크 받은 경우 응답 수정
  src/main/java/com/umc/DutchTogether/domain/settler/converter/SettlerConverter.java
  src/main/java/com/umc/DutchTogether/domain/settler/dto/SettlerResponse.java
  src/main/java/com/umc/DutchTogether/domain/settler/service/SettlerQueryServiceImpl.java
Labels: refactor

#127 [FIX] requestBody - settlementId 추가
  src/main/java/com/umc/DutchTogether/domain/payer/converter/PayerConverter.java
  src/main/java/com/umc/DutchTogether/domain/payer/dto/PayerResponse.java
Labels: fix

#129 [FIX] uniqueValidator 수정
  src/main/java/com/umc/DutchTogether/domain/settlementStatus/service/SettlementStatusCommandServiceImpl.java
  src/main/java/com/umc/DutchTogether/global/validation/validator/UniqueSettlerValidator.java
Labels: fix

#132 [REFACTOR] DTO,Entity annotation 정리
  src/main/java/com/umc/DutchTogether/domain/settlement/dto/SettlementRequest.java
Labels: refactor

#134 [FIX] CORS 에러 수정, 링크 받은 경우 응답 수정
  src/main/java/com/umc/DutchTogether/domain/meeting/converter/MeetingConverter.java
  src/main/java/com/umc/DutchTogether/global/config/WebConfig.java
Labels: fix
